/**
 * Single source of truth for the <Feature> messaging topology and event
 * payloads, shared across the API (producer), the worker (consumer) and the
 * web app. Nobody else declares exchange/queue names, routing keys or the
 * event shape — they all import from here.
 */
import { z } from "zod";
import { FeatureResultSchema } from "./dtos";

// ── Topology constants ────────────────────────────────────────────────────────
// These are plain strings (not from env) ON PURPOSE: the topology is part of
// the contract, identical for every side. Changing one here changes it for the
// producer, the consumer and the web at once.

/** Durable topic exchange the API publishes <Feature> events to. */
export const FEATURE_EXCHANGE = "feature.events";

/** Durable work queue the worker consumes from. */
export const FEATURE_QUEUE = "feature.worker";

/** Dead-letter exchange for poison / permanently-failed messages. */
export const FEATURE_DLX = "feature.events.dlx";

/** Dead-letter queue bound to the DLX (for inspection — never auto-requeued). */
export const FEATURE_DLQ = "feature.worker.dlq";

/** Routing keys used on the topic exchange. */
export const ROUTING_KEYS = {
  /** v1 — the current (base) event. */
  featureExecutedV1: "feature.executed.v1",
  // RULE for a future breaking change: add `featureExecutedV2: "feature.executed.v2"`
  // here, bump the event `version` literal to 2, keep this v1 key so old in-flight
  // messages still route, and confirm the `#` binding below still covers both.
} as const;

/**
 * Binding pattern the worker queue subscribes with.
 *
 * Uses `#` (zero-or-more words) so the current `feature.executed.v1` AND any
 * future sub-versioned key (e.g. `feature.executed.v2`) are all consumed.
 *
 * ⚠️ `*` (exactly-one-word) would SILENTLY drop a routing key with an extra
 * segment — e.g. the 3-word `feature.executed.v1` — so a POST would succeed but
 * nothing would ever persist. Always `#` when you sub-version routing keys.
 * A pure-logic coherence test should assert this pattern matches EVERY routing
 * key above (a topic matcher in plain JS, no broker needed).
 */
export const FEATURE_BINDING_PATTERN = "feature.#";

/**
 * Zod schema for the event emitted whenever the API accepts an inbound
 * <Feature> command. The schema is the single source of truth — the TypeScript
 * type is derived via z.infer so type and runtime validation can never diverge.
 *
 * Event versioning is explicit and machine-readable: `version` is a z.literal.
 * This is the BASE state (version 1, routing key `feature.executed.v1`).
 * - Additive evolution: add OPTIONAL fields, keep the routing key + version.
 * - Breaking change: bump the literal version AND the routing key segment
 *   (.v1 → .v2), and confirm the `#` binding still covers it.
 *
 * Identity (`messageId`) is generated by the PRODUCER (not the DB, not the
 * worker) and travels as: (a) this field, (b) the AMQP messageId header, and
 * (c) the idempotency target of the worker's ON CONFLICT DO NOTHING insert.
 * That is why at-least-once delivery is safe — dedup lives in the consumer.
 */
export const FeatureExecutedEventSchema = z.object({
  version: z.literal(1),
  messageId: z.string(),
  conversationId: z.string(),
  authorId: z.string(),
  /** Scope from the AUTHENTICATED context (verified JWT claim) — never user input. */
  tenantId: z.string(),
  body: z.string(),
  result: FeatureResultSchema,
  sentAt: z.string(), // ISO-8601, set by the producer's ClockPort
});

/** Emitted whenever the API accepts an inbound <Feature> command. */
export type FeatureExecutedEvent = z.infer<typeof FeatureExecutedEventSchema>;
